### ISSUE TITLE
Example use case: Simple noise estimation + masking

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/spectral-cube#119]
Here's an example I ran recently on some public ALMA data:

```
import spectral_cube
cube = spectral_cube.SpectralCube.read('calibrated.ms.contsub.bin4.line.fits')
noise = cube._apply_numpy_function(np.std, axis=0)
mcube = cube.with_mask(cube > noise)
m0 = mcube.moment0()

import aplpy
F = aplpy.FITSFigure(m0.hdu)
F.show_grayscale()
m0.hdu.writeto('m83_co_maskintegrated.fits')
```

The only problem is that it required the hidden `_apply_numpy_function`.  It relies on https://github.com/radio-astro-tools/spectral-cube/pull/115.  https://github.com/radio-astro-tools/spectral-cube/pull/100 would resolve the issue.

This is more of a "to-do" than an issue: once those other issues are resolved, this example can go in the docs (but it would sure be nice to have an astroquery query showing how to grab the data too...)

**Comment by e-koch** [comment]
We now have a tutorial for this: https://github.com/radio-astro-tools/tutorials/tree/master/masking_and_moments
