### ISSUE TITLE
wrong link on pipy

### ISSUE THREAD

**Issue by hamogu** [radio-astro-tools/spectral-cube#124]
On the pipy page for this project (https://pypi.python.org/pypi/spectral-cube) the link to the homepage is displayed as radio-astro-tools.github.com (which is right), but when I click on it it brings me to https://pypi.python.org/pypi/radio-astro-tools.github.com (which does not exist).

Mayby you need to include the `http:\\` part in the address?

**Comment by e-koch** [comment]
This appears to have been fixed at some point. The link points to the readthedocs page.
