### ISSUE TITLE
make_test_cubes failing on Travis builds

### ISSUE THREAD

**Issue by jzuhone** [radio-astro-tools/spectral-cube#177]
I noticed this on a recent [Travis build](https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/43912694) that actually was marked as passing:

```bash
python make_test_cubes.py
Traceback (most recent call last):
  File "make_test_cubes.py", line 6, in <module>
    from astropy.io import fits
ImportError: No module named astropy.io
make: *** [advs.fits] Error 1
```

Not sure if this is known or not.

**Comment by keflavich** [comment]
We haven't seen this for a while; I think it's fixed.
