### ISSUE TITLE
Question regarding moment calculation

### ISSUE THREAD

**Issue by jpinedaf** [radio-astro-tools/spectral-cube#183]
Hi,

I just started using spectral-cube (v0.2.dev672) and I have a couple of questions:
-Why is the beam information not preserved when calculating the moment maps?
-The original cube is stored in Ra-Dec-Freq, with the rest-frequency in the header. Is it possible to get the moment-0 in units of K km/s instead of K Hz?

This is the code I'm using at the moment (clearly not efficient, but it works):

```
    cube = SpectralCube.read(file_in)
    # Creates masks for line emission
    # This works but is not efficient!
    mask_mom=np.zeros( cube.shape, dtype=bool)
    mask_mom[index_peak] = True
    mask_mom = mask_mom & np.isfinite( (cube.unmasked_data[:,:,:]).value )
    cube_main = cube.with_mask(mask_mom)
       #calculate moment-0 and export fits file
        mom_0 = cube_main.moment(order=0)
        mom_0.write( file_in.replace('.fits', '_mom0.fits'))
```

**Comment by jpinedaf** [comment]
OK, I solved the second issue (unit conversion) but the first question is still there --Jaime

**Comment by keflavich** [comment]
@jpinedaf - Glad you solved the unit conversion issue.  `with_spectral_unit` is the tool if anyone else comes to this issue.

As for the lack of beam parameters - I think this is a bug and I'll investigate.  Check out the [radio-beam](https://github.com/radio-astro-tools/radio_beam) package for turning headers into astropy unit objects.

**Comment by keflavich** [comment]
Also, if you include some more information about `index_peak`, I can probably tell you how to make that snippet more efficient.

**Comment by jpinedaf** [comment]
Thanks! I'll check radio-beam.

In this case:  index_peak=np.arange(335,420)

**Comment by keflavich** [comment]
Oh, in that case, I think you could shorten your code to
```
mom_0 = cube[335:420].moment0()
```
but I'm not sure I read your intent exactly correctly.  Also, github tip: backticks around code (`) formats it nicely; triple backticks are good for code blocks

**Comment by jpinedaf** [comment]
Interesting. The moment calculation works only when I give an specific range of channels, but not if I try to select them using an array with indices:
```
In [30]: mom_0 = cube[600:800,:,:].moment(order=0)
In [31]: index_peak=np.arange(600,800)
In [32]: mom_0 = cube[index_peak,:,:].moment(order=0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-0d1ac2c9458c> in <module>()
----> 1 mom_0 = cube[index_peak,:,:].moment(order=0)

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spectral_cube-0.2.dev672-py2.7.egg/spectral_cube/spectral_cube.pyc in __getitem__(self, view)
    816                          copy=False,
    817                          unit=self.unit,
--> 818                          meta=meta)
    819 
    820         newmask = self._mask[view] if self._mask is not None else None

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spectral_cube-0.2.dev672-py2.7.egg/spectral_cube/spectral_cube.pyc in __new__(cls, value, unit, dtype, copy, wcs, meta, mask)
    135 
    136         if np.asarray(value).ndim != 2:
--> 137             raise ValueError("value should be a 2-d array")
    138 
    139         if wcs is not None and wcs.wcs.naxis != 2:
ValueError: value should be a 2-d array
```

Is this the expected behaviour? Since I will be using an user defined channel range I need to use the array :(

**Comment by keflavich** [comment]
@jpinedaf - there is currently no support for creating sub-cubes with discontinuous spectral axes.  Still, the error you got is not the intended response.  

A workaround that will work once I [fix a bug](https://github.com/radio-astro-tools/spectral-cube/pull/189) that it has revealed (sorry....) is:

```
cube = SpectralCube.read('grs-48-cube.fits')
inds = np.arange(cube.shape[0])
mask = (inds < 100) | (inds > 400)
cube.with_mask(mask[:,None,None]).moment0()
```
So you use your `index_peak` to create a boolean array mask and mask the cube with that before computing the moment.  That will be reasonably efficient and should address *most* use cases.
