### ISSUE TITLE
does not parse JY/BEAM unit

### ISSUE THREAD

**Issue by jpinedaf** [radio-astro-tools/spectral-cube#214]
The ``BUNIT`` FITS keyword from CASA is in uppercase, which makes it incompatible with the default behaviour in astropy.units. The result are cubes without units:
```
In [5]: from spectral_cube import SpectralCube
In [6]: cube11sc = SpectralCube.read(OneOneFile)
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spectral_cube-0.2.dev769-py2.7.egg/spectral_cube/spectral_cube.py:103: UserWarning: Could not parse unit JY/BEAM
  warnings.warn("Could not parse unit {0}".format(self._meta['BUNIT']))
In [17]: cube11sc.unit
Out[17]: Unit(dimensionless)
```

The FITS header shows the following
```
BUNIT   = 'JY/BEAM '           /Brightness (pixel) unit
```

The obvious workaround is to assign the unit manually
```
In [19]: cube11sc._unit  = u.Unit('Jy/beam')
```
however, it kind of defeats the purpose. 

I'm using the latest spectral-cube (v0.2.dev769) and astropy v1.0.1.

**Comment by astrofrog** [comment]
Note: JY/BEAM is not FITS standard compliant so this should be reported to the CASA devs - I'm sure other people have reported it before, but the more people report it the better :)

Having said that, we should probably include a workaround.

**Comment by jpinedaf** [comment]
Agreed. It looks like JY/BEAM has been changed to the proper Jy/beam at some point after CASA 4.2.1. However, JY/BEAM is still present in legacy files... and I'm not sure about what is AIPS doing.

**Comment by keflavich** [comment]
This is addressed - albeit inadequately - in https://github.com/radio-astro-tools/spectral-cube/pull/184.  Further discussion should go there.
