### ISSUE TITLE
NaN handling problems in plots?

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/spectral-cube#215]
@e-koch this is referencing https://github.com/camelot-project/database/pull/107

Are there problems handling nan entries in tables when plotting?

**Comment by e-koch** [comment]
@keflavich - Wrong repo? I thought it would be, but matplotlib seems to be handling it.

**Comment by keflavich** [comment]
....yes, wrong repo... don't know how that happened, thanks.
