### ISSUE TITLE
Bug in write function: not keeping beam parameters

### ISSUE THREAD

**Issue by jpinedaf** [radio-astro-tools/spectral-cube#237]
There is a bug in the write function. Now that `SpectralCube` handles the beam size (#236), it should write it out as well. In the current implementation it makes `BMIN=BMAJ`. 

```
In [39]: from spectral_cube import SpectralCube
In [40]: cube=SpectralCube.read('L1451mm/L1451MM-11_cvel_clean_rob05.fits')
In [41]: cube.beam
Out[41]: Beam: BMAJ=3.08794236183 arcsec BMIN=2.61326932907 arcsec BPA=-19.7857666016 deg
In [42]: cube.write('test.fits')
In [44]: cube2=SpectralCube.read('test.fits')

In [45]: cube2.beam
Out[45]: Beam: BMAJ=3.08794236183 arcsec BMIN=3.08794236183 arcsec BPA=-19.7857666016 deg
```

**Comment by e-koch** [comment]
@jpinedaf - Is ```BMIN=BMAJ``` in ```cube2.header```? This could be a bug in ```radio_beam```.

It's probably time to turn Travis on for radio_beam.

**Comment by jpinedaf** [comment]
The FITS header of cube2 shows `BMIN = BMAJ`
```
In [10]: !fitshdr test.fits | grep BMIN
BMIN    =   0.0008577617671755
                                                                                
In [11]: !fitshdr test.fits | grep BMAJ
BMAJ    =   8.577617671755E-04
```

**Comment by e-koch** [comment]
This is a bug in ```Beam.attach_to_header``` in radio_beam.

**Comment by e-koch** [comment]
@keflavich - I can't merge anymore. Can you merge please?

**Comment by e-koch** [comment]
@jpinedaf - The PR in radio_beam fixes this.
