### ISSUE TITLE
tests fail due to missing fits files

### ISSUE THREAD

**Issue by olebole** [radio-astro-tools/spectral-cube#254]
Hi, I am working on improving the build process for the spectral-cube Debian package.

When I run "python setup.py test", I get a number of error that are connected to missing FITS files in `spectral_cube/tests/data/`: `vda.fits`, `advs.fits` and so on. These are probably missing due to size constraints, right?
Since there are quite many tests that still succeed (I get 179 failed, 186 passed, 9 skipped, 1 xfailed, 56 error), it would be nice to mark those that need additional files so that one could do some tests on installation and as a CI test.

**Comment by keflavich** [comment]
@olebole there is a pre-setup step to get the tests to run:
https://github.com/radio-astro-tools/spectral-cube/blob/master/.travis.yml#L169
but you're right, we should have a flag on tests that require this data to be in place.

**Comment by olebole** [comment]
The command to actually prepare the test data is `cd spectral_cube/tests/data ; make ; cd ../../../`, right? But, in `spectral_cube/tests/data` there is no Makefile (and no `make_test_cubes.py`) in the [pypi tar file](https://pypi.python.org/packages/source/s/spectral-cube/spectral-cube-0.3.0.tar.gz).

**Comment by keflavich** [comment]
Sorry, I completely lost track of this.  I guess this is a problem in the source packaging.  @astrofrog, could you chime in on this?

**Comment by olebole** [comment]
The tests now succeed, since the missing files are packaged. So, from my side this is solved; I am closing it.
