### ISSUE TITLE
Adding more functionality to Projection

### ISSUE THREAD

**Issue by e-koch** [radio-astro-tools/spectral-cube#279]
`BaseNDClass` should allow for `Projection` and `Slice` objects to access to the spatial world coordinate abilities of `SpectralCube` (longitude, latitude, extrema, etc...).

**Comment by keflavich** [comment]
Sounds kind of reasonable.  Want to make a checklist for things you think could be common to all?

**Comment by e-koch** [comment]
WIth `world` generalized for 2D projections, all of these become trivial to include.

* [ ] spatial_coordinate_map
* [ ] world
* [ ] world_extrema
* [ ] flattened_world
* [ ] longitude_extrema
* [ ] latitude_extrema
* [ ] "subcube" like behaviour, where slicing with world coordinates is accepted

This probably is not an exhaustive list yet.

**Comment by keflavich** [comment]
@astrofrog we're likely to be able to implement a lot of this, and so we probably will.  Again, I wonder to what degree this overlaps/clashes with `astropy.nddata`.  We're living heavily on the functionality-driven side in spectral-cube, but we've now abstracted enough that I expect there to be some competition and/or possibly reusable resources.

**Comment by e-koch** [comment]
This will also require a `apply_numpy_function` type function for the lower dimensional objects. Using built-in numpy functions like `proj.mean()` returns a `Projection`, not a `Quantity`.

**Comment by keflavich** [comment]
Perhaps instead that should mean that `BaseNDClass` would not include any of the `apply_numpy_function` etc. functionality, and that would only go into `SpectralCube`?  Since those are meant to provide means to deal with very large data sets, they aren't necessary for lower-dimensional objects.

**Comment by keflavich** [comment]
How much of this has been done?  Some for sure...

**Comment by e-koch** [comment]
Finished off in #575.
