### ISSUE TITLE
bug in spatial coordinates?

### ISSUE THREAD

**Issue by astroklaassen** [radio-astro-tools/spectral-cube#280]
I've got a bunch of (ALMA) spectral cubes which, when I read in to SpectralCube, end up getting shifted by a couple of arcmin (in both RA and DEC).  This includes example cubes I've created myself, and those created by someone else. I noticed this shift when I tried to plot continuum contours on top of a moment map to find the new map was spatially offset outside my primary beam.

The input cubes haven't been modified since they were exported from CASA images (one set created with dropstokes=True, the other set with the degenerate axis left in). This happens before I do any processing to the cube, i.e. the simple case of:

```
cube = SpectralCube.read(infile)
cube.write(outfile)
```

already corrupts the spatial coordinate information (the spectral limits remain unchanged).

I've attached two screen captures showing the FOV of the original FITS cube, and that output from Spectral Cube (in this case, a cube with a degenerate stokes axis)
<img width="338" alt="orig_cube_coordinates" src="https://cloud.githubusercontent.com/assets/17299695/13119624/0a26aa52-d5a2-11e5-8054-7c6f0ad0287f.png">
<img width="344" alt="spectralcube_coordinates" src="https://cloud.githubusercontent.com/assets/17299695/13119625/0a2ae05e-d5a2-11e5-938f-bfe35b0bea25.png">

any suggestions?

possibly related, when I import the cubes, I get a number of warnings along the lines of:

> WARNING: FITSFixedWarning: PC01_01 = 1.000000000000E+00
> indices in parameterized keywords must not have leading zeroes. [astropy.wcs.wcs]

which I haven't been able to work through, since those header keywords don't seem to have any leading zeros.

Versions:
spectral_cube: 0.3.1
python: 2.7
(ipython 3.1.1)
astropy 1.1.1
(mostly installed with anaconda - not anaconda2)

**Comment by keflavich** [comment]
Could you send over a full copy of a header (or post it here)?

**Comment by astroklaassen** [comment]
full fits cube sent.

**Comment by keflavich** [comment]
This is a major bug, and it's not in spectral-cube, it's in astropy.wcs.  I'll post something upstream.  The CRVAL values are getting ridiculously truncated!

**Comment by astroklaassen** [comment]
Thanks for the update. glad it's not just me.

**Comment by keflavich** [comment]
@astroklaassen if you pull the latest astropy master, this issue is fixed.  I was also using an out-of-date astropy; I think this issue was fixed within the last ~2 weeks.

**Comment by keflavich** [comment]
the issue was fixed by this commit:
https://github.com/astropy/astropy/pull/4579

**Comment by astroklaassen** [comment]
updated astropy master, and, as expected, the coordinates are no longer truncated.

Thank you very much.
