### ISSUE TITLE
spectral_cube and radio_beam package?

### ISSUE THREAD

**Issue by aakepley** [radio-astro-tools/spectral-cube#286]
When opening a FITS cube in spectral_cube, I get the following error message:

```
import numpy as np
import matplotlib.pyplot as plt
import pyregion
from spectral_cube import SpectralCube

cube = SpectralCube.read(fitsFile)

/Users/amanda/anaconda/lib/python2.7/site-packages/spectral_cube/spectral_cube.py:252: UserWarning: radio_beam is not installed. No beam can be created.
  warnings.warn("radio_beam is not installed. No beam "
/Users/amanda/anaconda/lib/python2.7/site-packages/spectral_cube/spectral_cube.py:263: UserWarning: Could not parse beam information from header.  Exception was: UnboundLocalError("local variable 'Beam' referenced before assignment",)
  "  Exception was: {0}".format(ex.__repr__()))
```

Looks like radio_beam needs to be installed, but pip wasn't able to find the package (either radio_beam or radio-beam). Should I be installing it another way? Apologies if this is a really basic question.

**Comment by keflavich** [comment]
You can install it directly from here:
https://github.com/radio-astro-tools/radio_beam
e.g. with:
`pip install https://github.com/radio-astro-tools/radio_beam/archive/master.zip`

We haven't made a pip release of `radio_beam` yet.  

However, this looks like a real error that we should fix.  Are you on the latest development version of spectral-cube or the pip version?

**Comment by aakepley** [comment]
I'm using the pip version of spectral-cube.

**Comment by keflavich** [comment]
Installing `radio_beam` from the above URL should solve your problem.

This will stay open as an issue, though, because we would like to give a more useful error message if `radio_beam` is not installed.

**Comment by aakepley** [comment]
I can confirm that I did install radio_beam from the URL and it solved my issue. I agree that a more useful error message would be helpful.

**Comment by kristina-monsch** [comment]
Hi! I just stumbled upon this issue and I have a question that might be related in some sense. I have been working successfully with radio-beam and want to reference the package in my paper, but I can't find a proper reference for it. Is there a paper or something that I should use for reference?

**Comment by astrofrog** [comment]
@adamginsburg - I think we can close this since we now have it as a dependency?
