### ISSUE TITLE
Issue with sphinx theme on RTD

### ISSUE THREAD

**Issue by astrofrog** [radio-astro-tools/spectral-cube#295]
Back to the 90s: http://spectral-cube.readthedocs.io/en/latest/

**Comment by cdeil** [comment]
Oh 👨  ... this makes my 👀  :hurtrealbad: !

**Comment by cdeil** [comment]
Also, there's no search field ... makes it really hard to find something.
Can one of you please fix or should I have a look?

**Comment by keflavich** [comment]
@cdeil please have a look - I don't know what broke, but spectral-cube originally used the astropy theme.  Something changed in the past ~year.
