### ISSUE TITLE
Broken API links in doc

### ISSUE THREAD

**Issue by pllim** [radio-astro-tools/spectral-cube#338]
In [Creating/reading spectral cubes](http://spectral-cube.readthedocs.io/en/latest/creating_reading.html) section, the reference to `read()` method does not produce a working link to its API. This is because `BaseSpectralCube` is not included in the API documentation.

Also happens to other methods and attributes referenced throughout the entire documentation.

**Comment by astrofrog** [comment]
Working on it.

**Comment by pllim** [comment]
Just realized this is similar to #323
