### ISSUE TITLE
Doc: Arithmetic clarifications

### ISSUE THREAD

**Issue by pllim** [radio-astro-tools/spectral-cube#341]
In the [Spectral Cube Arithmetic](http://spectral-cube.readthedocs.io/en/latest/arithmetic.html) section, it is cautioned that copies of the whole cube will be made. However, is this still true if I only want to do arithmetic on slices of cubes? For example:

```python
cube2 = cube[0, :, :] * 2
```

Will this make a copy only of `cube[0, :, :]` or the entire `cube`?

**Comment by keflavich** [comment]
`cube[0,:,:]` is a `Slice`, a `LowerDimensionalObject`, so it would only copy that slice of the cube, not the whole cube.

**Comment by pllim** [comment]
That's good to know and I think should be included in the doc. Currently, the existing text sounds very ominous and implies that user should avoid arithmetic on spectral cubes unless they want memory problems.
