### ISSUE TITLE
Normalizing convolution kernels

### ISSUE THREAD

**Issue by e-koch** [radio-astro-tools/spectral-cube#388]
There's no warning or checks in place if a convolution kernel is not well-sampled on the pixel grid. This is going to arise often when trying to convolve a `VaryingResolutionSpectralCube` to a common beam size when the beams differ by far less than the pixel size.

Should we force the deconvolved beam to be oversampled? Or can we force the kernel to be normalized with `normalize_kernel=True` in the convolve function (which would only work for the astropy convolve functions)?

Our tests suffer quite badly from this issue: in `test_regrid.test_convolution` the kernel is severely truncated (`expected.truncation=0.61468841132795915`).

**Comment by keflavich** [comment]
I don't think there's any way to oversample the kernel because it has to be on exactly the same grid.  Forcing it to be normalized makes sense though.

**Comment by e-koch** [comment]
Fixed in #389
