### ISSUE TITLE
Warnings when tab-completing

### ISSUE THREAD

**Issue by astrofrog** [radio-astro-tools/spectral-cube#412]
I have loaded a cube and don't have radio_beam installed - every time I type ``cube.`` then tab-complete, I get the following warnings:

```
WARNING: A 'NAXIS1' keyword already exists in this header.  Inserting duplicate keyword. [astropy.io.fits.header]
WARNING: A 'NAXIS3' keyword already exists in this header.  Inserting duplicate keyword. [astropy.io.fits.header]
/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/spectral_cube/spectral_cube.py:246: UserWarning: Could not parse beam information f
  "  Exception was: {0}".format(ex.__repr__()))
/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/spectral_cube/spectral_cube.py:238: UserWarning: radio_beam is not installed. No be
```

If I try and tab complete three times, I get all this three times over, which makes my IPython session unreadable.

**Comment by keflavich** [comment]
What version of ipython are you using?  I'm pretty sure this is an ipython bug, not a spectral_cube bug.  See, e.g., https://github.com/pandas-dev/pandas/issues/16409

**Comment by keflavich** [comment]
@astrofrog - can you confirm whether this is an ipython or spectral cube bug?  I'd like to close it if it's not ours.

**Comment by keflavich** [comment]
I'm pretty sure this issue went away and was a temporary thing.
