### ISSUE TITLE
Add radio_beam as a dependency

### ISSUE THREAD

**Issue by astrofrog** [radio-astro-tools/spectral-cube#415]
I would like to suggest that we add radio_beam in ``setup.py`` now that there is a release. I don't think it will stop non-radio users from using the package, it's simply that we use this dependency to support radio cubes. And radio-beam is a pretty lightweight dependency!

**Comment by keflavich** [comment]
I'm OK with this.  A PR would be welcome.  I'll try to issue a new release of spectral-cube next week...

**Comment by olebole** [comment]
Hmm, this means that I need to package radio_beam now before I can update spectral_cube in Debian.
