### ISSUE TITLE
Convolution of a data cube produced by a radiative transfer code

### ISSUE THREAD

**Issue by smaret** [radio-astro-tools/spectral-cube#432]
I'm trying to use the `.convolve_to()` method to convolve a cube produced by a radiative transfer code, but I'm getting the following error:

```python
>>> cube = SpectralCube.read("CO.fits.gz")
WARNING: FITSFixedWarning: 'spcfix' made the change 'Changed CTYPE3 from 'VELO-LSR' to 'VOPT', and SPECSYS to 'LSRK' (VELREF=0)'. [astropy.wcs.wcs]
/usr/local/lib/python2.7/site-packages/spectral_cube/spectral_cube.py:246: UserWarning: Could not parse beam information from header.  Exception was: TypeError('No BMAJ found and does not appear to be a CASA/AIPS header.',)
  "  Exception was: {0}".format(ex.__repr__()))
>>> cube = cube.convolve_to(beam)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/spectral_cube/spectral_cube.py", line 2630, in convolve_to
    convolution_kernel = beam.deconvolve(self.beam).as_kernel(pixscale)
AttributeError: 'SpectralCube' object has no attribute 'beam'
```

Indeed, the data cube has no beam information since it comes from a radiative transfer code. But why a cube needs to have a beam attribute to be convolved in the first place?

**Comment by keflavich** [comment]
The `convolve_to` function convolves to a specified resolution; in order to
do so, it must know the original resolution.  We can expose another
function `convolve_with` which would convolve with any user- specified
kernel.  I'll implement that.

**Comment by e-koch** [comment]
@keflavich - `SpectralCube.spatial_smooth` should do that already. The docs don't mention it yet, though.

But it would be handy to be able to pass your own `Beam` into `SpectralCube` too. Starting with a point-like beam seems like a common starting point with synthetic observations.

**Comment by keflavich** [comment]
Oh, right, thanks.

And yes, a pointlike beam would be nice to have available... I don't know if that works with the deconvolve tools.

**Comment by keflavich** [comment]
Apparently the docstring doesn't even show up in our docs, but this is the relevant function: https://github.com/radio-astro-tools/spectral-cube/blob/master/spectral_cube/spectral_cube.py#L2384

**Comment by smaret** [comment]
Thanks for your answers. I agree it would be nice to be able to pass a 'Beam' instance to a `SpectralCube`.

As a quick workaround to my specific problem, I've simply added a `BMAJ` keyword to the FITS cube with the pixel size. It's not 100% correct though because pixels are not Gaussian, but it should be OK when the pixel size is small compared to beam size for the convolution.

**Comment by keflavich** [comment]
@smaret can you do the convolution you want *without* adding a beam by using the `spatial_smooth` method?  That would be the more correct way to do what I think you're trying to do.

**Comment by smaret** [comment]
> can you do the convolution you want without adding a beam by using the spatial_smooth method?

Done. It works fine, thanks!
