### ISSUE TITLE
Unit is dropped when creating cube from scratch

### ISSUE THREAD

**Issue by astromichael** [radio-astro-tools/spectral-cube#447]
relevant code shown below:

`In [2]: cube`
`Out[2]: `
`SpectralCube with shape=(120, 601, 935) and unit=K:`
` n_x:    935  type_x: RA---ARC  unit_x: deg    range:   202.411584 deg:  202.526182 deg`
` n_y:    601  type_y: DEC--ARC  unit_y: deg    range:    47.169981 deg:   47.219995 deg`
` n_s:    120  type_s: VRAD      unit_s: m / s  range:  -297500.000 m / s:  297500.000 m / s`

`In [3]: SpectralCube(data=cube.filled_data[:, :, :], wcs=cube.wcs)`
`Out[3]: `
`SpectralCube with shape=(120, 601, 935):`
` n_x:    935  type_x: RA---ARC  unit_x: deg    range:   202.411584 deg:  202.526182 deg`
` n_y:    601  type_y: DEC--ARC  unit_y: deg    range:    47.169981 deg:   47.219995 deg`
` n_s:    120  type_s: VRAD      unit_s: m / s  range:  -297500.000 m / s:  297500.000 m / s`

**Comment by keflavich** [comment]
Good catch, this is a bug.  It's resolved in #448

**Comment by keflavich** [comment]
Closed by #448
