### ISSUE TITLE
Multi-threading compatibility of SpectralCube Smoothing Functions

### ISSUE THREAD

**Issue by robelgeda** [radio-astro-tools/spectral-cube#452]
Hello, I am working on CubeViz at STScI and we were hoping to use Spectral Cube's smoothing capeblities. The current version of SpectralCube.smoothing functions use [astropy.utils.console.ProgressBar](https://github.com/radio-astro-tools/spectral-cube/blob/cc90374cb3a8efdeb3e5d32731b1178b08b29281/spectral_cube/spectral_cube.py#L2480) which demanded that the smoothing function be executed on the main thread. Since we are using a GUI, this causes significant competition for resources. It would help us a great deal if I can add the option of 'turning off' the `astropy.utils.console.ProgressBar` in the smoothing functions. We are also interested in adding the ability to abort smoothing mid-calculation and updating a pyqt `QProgressBar`. I have made a #454  that would resolve our issues.

**Comment by keflavich** [comment]
I'm happy to see the `ProgressBar` become optional, so please submit your PR.  Note that the link in the original post here points back to this issue (#452), so it appears you have not yet submitted the PR.

**Comment by robelgeda** [comment]
Hi @keflavich! Thank you! I just submitted a [PR](#454).
