### ISSUE TITLE
ImportError: No module named _moments

### ISSUE THREAD

**Issue by 3rico** [radio-astro-tools/spectral-cube#515]
When i try compute moments by: 

cube.moment0()

i get the following error: 

ImportError                               Traceback (most recent call last)
<ipython-input-9-906d737235e0> in <module>()
----> 1 cube.moment0()

/usr/local/lib/python2.7/dist-packages/spectral_cube/spectral_cube.pyc in moment0(self, axis, how)

/usr/local/lib/python2.7/dist-packages/spectral_cube/spectral_cube.pyc in moment(self, order, axis, how)

ImportError: No module named _moments

**Comment by keflavich** [comment]
This looks like an installation failure, and it's a weird one.  Could you try re-installing, and also report what version of spectral-cube you're using?

**Comment by e-koch** [comment]
As this was with an old spectral-cube version and we no longer support python 2, I'm going to close this.

Re-open if the issue shows up elsewhere with the current version.
