### ISSUE TITLE
Computing 1st moment for data cube results in unexpected values and units

### ISSUE THREAD

**Issue by kakirastern** [radio-astro-tools/spectral-cube#526]
Hi, I have been using SpectralCube to compute the 1st moment of a data cube, in order to obtain the velocity structure for a planetary nebula (PN). However, I obtained some unexpected quantities (both values and units) for all spaxels. I was studying a PN with a very well known radial velocity, so I have in mind a very specific range of values in km/s for it. However, the moment() function with both a unit (output: m/s) and values (output: around 6000) which did not make any sense to me. I have double checked my calculations with PyRAF's `RVSAO` package, using the `EMSAO` and `XCSAO` tasks in conjunction, which yield a range of quantities of around 60000 m/s or 60 km/s before heliocentric velocity correction (HCV) was applied. I would like to know if there this is indeed due to a bug or some other issue. Is this a known issue?

**Comment by keflavich** [comment]
No, there are no known issues similar to what you reported.   Have you
inspected the spectra?  Also, what units were unexpected?  It sounds like
you expected and got velocity units.

**Comment by keflavich** [comment]
Also, if you end up with a nice contained example, it would be really helpful to add it as a tutorial on http://astropy-tutorials.readthedocs.io/.

**Comment by kakirastern** [comment]
@keflavich Awesome, that sounds like a good idea! I will definitely use my data and experience to write a tutorial for the moment map facility of SpectralCube... I think I actually have to turn my 1D raw spectrum count rate vs. wavelength in the 3rd dimension into `vopt` velocities somehow. Am looking into the matter. Will surely follow up as I will be able to use my own documentation as a future reference too.

**Comment by keflavich** [comment]
you likely want to use `with_spectral_unit` to make that conversion; it wraps a set of low-level tools for spectral axis conversion that, at present, only exist within spectral-cube (though they should eventually be put into astropy-core)

**Comment by kakirastern** [comment]
Thanks for the tip! I appreciate it.
