### ISSUE TITLE
Add example for alternative approach to spatial smoothing

### ISSUE THREAD

**Issue by kakirastern** [radio-astro-tools/spectral-cube#547]
I have been carrying out spatial smoothing using the following code: 
```
>>> from spectral_cube import SpectralCube
>>> from astropy.io import fits
>>> from astropy.convolution import Gaussian2DKernel
>>> cube0 = fits.open('/some_path/IC418_bluearm_mosaic.fits')
>>> cube = SpectralCube.read(cube0)
>>> kernel = Gaussian2DKernel(1)
>>> new_cube = cube.spatial_smooth(kernel)
>>> new_cube.write('/some_path/IC418_bluearm_mosaic_smoothed.fits')
```
This approach has not yet been incorporated into the `spectral-cube` docs. Is it okay for me to open a PR to add this, if such usage is encouraged on top on the one currently documented in the docs using the `beam` or `beams` attribute at [https://spectral-cube.readthedocs.io/en/latest/smoothing.html#spatial-smoothing](https://spectral-cube.readthedocs.io/en/latest/smoothing.html#spatial-smoothing).

**Comment by keflavich** [comment]
Yes, please do.  You'll need to define `kernel` in the example.

**Comment by kakirastern** [comment]
Yup, added the definition of kernel both to the example above and in the spectral_cube code base in PR #548. Thanks for pointing out the omission!
