### ISSUE TITLE
Spectral line detection and fitting?

### ISSUE THREAD

**Issue by theparmis** [radio-astro-tools/spectral-cube#569]
Hello,
Is it possible to detect a spectral line (name) corresponding to specific frequency? 
Since as we read data from cubes, we can visualize each peaks in every frequencies, But I guess it's not possible to fit a distribution over a spectral line to obtain integrated flux or peak flux. Is there any feature to detect spectral line from spectral-cube or Astropy even? 

That would be great if there is any help from spectral-cube package!

**Comment by e-koch** [comment]
https://pyspeckit.readthedocs.io/en/latest/ or https://docs.astropy.org/en/stable/modeling/ might be closer to what you're looking for.
