### ISSUE TITLE
help with getting started

### ISSUE THREAD

**Issue by trhunter** [radio-astro-tools/spectral-cube#570]
I am trying to use spectral_cube for this first time (latest git clone) on CASA cubes.  The example in the docs for reading a cube seems to be out of date:

```
# Read in spectral cube
cube = SpectralCube.read('L1448_13CO.fits', format='fits')
```

With that syntax, I get an error  that init takes at least 3 arguments (2 given).  It seems that wcs is now required.  What exactly is it expecting for that parameter?

Todd

**Comment by keflavich** [comment]
That's... weird.  That is the correct syntax and should not have resulted in any error.  Could you give a full traceback w/the syntax you've actually used (i.e., the 'true' filename)?

**Comment by trhunter** [comment]
OK, I had failed to type the ".read" part of the syntax.  Now it loads.  Next I need to figure out how to get the yt module installed.
