### ISSUE TITLE
I broke the build by merging something green

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/spectral-cube#580]
We are on a "broken master" caused by upstream changes.  It looks like there are several independent, simultaneous failures.

https://travis-ci.org/radio-astro-tools/spectral-cube/builds/590110581

* [ ] python2.7 + numpy 1.17 won't build.   https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/590110587#L877
* [ ] reproject doesn't take independent_celestial_slices (https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/590110589#L2039): is this a version issue?
* [ ] Some totally wacky message (https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/590110588#L1404) that probably points back to incompatibilities:
ERROR: reproject 0.6.dev0 has requirement astropy>=3.2, but you'll have astropy 2.0.14 which is incompatible.
ERROR: reproject 0.6.dev0 has requirement numpy>=1.13, but you'll have numpy 1.11.3 which is incompatible.

I'm going to try dropping _testing_ for old things (py2, astropy-LTS), so we're "dropping support" for these, but I still want them to work...

**Comment by astrofrog** [comment]
The independent_celestial_slices argument is no longer needed but I should add a deprecation warning to reproject!

**Comment by astrofrog** [comment]
Also reproject dev requires astropy 3.2 - of course you can still support old versions of reproject but if you are testing against reproject dev you’ll need astropy 3.2+

**Comment by astrofrog** [comment]
Just to clarify, what I mean is that I don’t think you should have to drop testing for old versions - just don’t rely on reproject dev for those builds
