### ISSUE TITLE
DS9 "panda" region?

### ISSUE THREAD

**Issue by zschaech** [radio-astro-tools/spectral-cube#587]
Is it correct that DS9 "panda" is unsupported?  Adding additional DS9 regions was on the to-do list for CASA... any chance its on the spectral-cube to-do list as well?  :-)

**Comment by keflavich** [comment]
spectral-cube uses astropy regions directly, so you should post this there instead.  And, yeah, maybe pandas will get implemented, but it depends on who's willing to work on it.

**Comment by zschaech** [comment]
Thanks!  That was fast!
