### ISSUE TITLE
Don't use casatasks

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/spectral-cube#597]
`import casatasks` seems to import matplotlib and initialize a matplotlib plot window, so we should not use anything from `casatasks` (only `casatools`).

@astrofrog this means the `exportfits` trick is off-limits; we need a different option.

**Comment by keflavich** [comment]
Closed by https://github.com/radio-astro-tools/spectral-cube/pull/595/commits/bf31d83320d1233fe1ca9ed6078e51bf7b4f899d

**Comment by preshanth** [comment]
You can always use ia.tofits which is only the tool level method that is called under exportfits.
`        myia = image( )
         myia.open(imagename)
         myia.tofits( outfile=fitsimage, velocity=velocity, optical=optical,
                      bitpix=bitpix, minpix=minpix, maxpix=maxpix,
                      overwrite=overwrite, dropstokes=dropstokes, stokeslast=stokeslast,
                      history=history, dropdeg=dropdeg )
         myia.close( )'

**Comment by keflavich** [comment]
@preshanth thanks, that's the solution we adopted
