### ISSUE TITLE
patch **kwargs passing in convolution

### ISSUE THREAD

**Issue by akleroy** [radio-astro-tools/spectral-cube#630]
In convolution, convfunc is defined as a convenience function but drops the **kwarg passing. Line 3124 or so:

        def convfunc(img):
            return convolve(img, convolution_kernel, normalize_kernel=True,
                            **kwargs)

Can this be updated to:

        def convfunc(img, **kwargs):

please.

Thank you!

**Comment by akleroy** [comment]
Or if I'm just screwing something up let me know and close the ticket.

**Comment by keflavich** [comment]
Yes, make a pr!

**Comment by keflavich** [comment]
So, the kwargs are already being passed to `convolve` directly, they're circumventing the intermediate `convfunc`.  I'm not sure there's any advantage - or harm - in the approach you've suggested.  Let's continue discussion on #631

**Comment by e-koch** [comment]
Fixed in #631
