### ISSUE TITLE
plot_channel_maps

### ISSUE THREAD

**Issue by gvdsteene** [radio-astro-tools/spectral-cube#649]
How can I easily plot all channel maps of my cube, please ?
I keep on running into error messages and I cannot find any example in the docs (nor in the casa docs, on how to put it in a script)

```
sub_cube.plot_channel_maps(3,3,channels=[1:9])
  File "<stdin>", line 1
    sub_cube.plot_channel_maps(3,3,channels=[1:9])
                                              SyntaxError: invalid syntax
sub_cube.plot_channel_maps(3,3,channels=[1,2,3,4,5,6,7,8,9])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/spectral_cube/spectral_cube.py", line 3398, in plot_channel_maps
    gs = GridSpec(ny, nx, figure=fig, hspace=0, wspace=0)
TypeError: __init__() got an unexpected keyword argument 'figure'
>>> sub_cube.plot_channel_maps(3,3,channels=[1,2,3,4,5,6,7,8,9],output_file='test',fig=fig)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'fig' is not defined
>>> sub_cube.plot_channel_maps(3,3,channels=[1,2,3,4,5,6,7,8,9],output_file='test',fig='test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/spectral_cube/spectral_cube.py", line 3391, in plot_channel_maps
    fig.set_figheight(ysize)
AttributeError: 'str' object has no attribute 'set_figheight'
```

**Comment by keflavich** [comment]
What version of matplotlib do you have?  This line:
`TypeError: __init__() got an unexpected keyword argument 'figure'`
is coming from `matplotlib.gridspec.GridSpec`, which does accept a `figure=` argument (https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.gridspec.GridSpec.html)

Your other failures are simply incorrect uses of the documented function.  `fig` must be a `Figure` instance, not a string:
https://spectral-cube.readthedocs.io/en/latest/api/spectral_cube.SpectralCube.html#spectral_cube.SpectralCube.plot_channel_maps

**Comment by keflavich** [comment]
I'm closing this as solved - with the correct version of matplotlib, this should work.
