### ISSUE TITLE
Fast global stats?

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/spectral-cube#659]
CASA's `ia.statistics` is pretty fast.  We should probably try to have a convenience function that does similar, e.g.:
```
                    min = cube.min()
                    max = cube.max()
                    mad = cube.mad_std()
                    std = cube.std()
                    sum = cube.sum()
                    mean = cube.mean()
```
but all at once.  Can `dask` handle doing all of this in a "single pass" - i.e., run all the stats computations in parallel with a single io read?

**Comment by astrofrog** [comment]
Done in #663
