### ISSUE TITLE
allow_huge=False in convolve_fft

### ISSUE THREAD

**Issue by foxmouldy** [radio-astro-tools/spectral-cube#696]
I am trying to convolve a cube to a new beam: 

`bmaj_new = 12.`
`new_beam = radio_beam.Beam(major=bmaj_new*u.arcsec, minor=bmaj_new*u.arcsec, pa=0*u.deg)`
`cube_beam_smoothed = cube.convolve_to(new_beam)`

The cube is 4k x 4k pixels and 16 channels. 

I use `cube.allow_huge_operations = True`, but this isn't passed to convolve_fft, thus resulting in the following error:

`/anaconda3/lib/python3.6/site-packages/astropy/convolution/convolve.py in convolve_fft(array, kernel, boundary, fill_value, nan_treatment, normalize_kernel, normalization_zero_tol, preserve_nan, mask, crop, return_fft, fft_pad, psf_pad, min_wt, allow_huge, fftn, ifftn, complex_dtype)
    686         raise ValueError("Size Error: Arrays will be {}.  Use "
    687                          "allow_huge=True to override this exception."
--> 688                          .format(human_file_size(array_size_C)))
    689 
    690     # For future reference, this can be used to predict "almost exactly"
ValueError: Size Error: Arrays will be 1.0G.  Use allow_huge=True to override this exception
`

Solution: pass the value of `allow_huge_operations` in `cube.convolve_to` to `convolve_fft`

**Comment by keflavich** [comment]
Good catch, thanks!  Would you like to submit your proposed fix as a pull request?

**Comment by e-koch** [comment]
This is a good solution!

In case anyone else encounters this error before the fix is added, `cube.convolve_to(new_beam, allow_huge=True)` can also be used.

**Comment by e-koch** [comment]
Fixed in #725
