### ISSUE TITLE
Test failures with radio-beam 0.3.3

### ISSUE THREAD

**Issue by rmcgibbo** [radio-astro-tools/spectral-cube#708]
I noticed some test errors when updating from radio-beam 0.3.2 to radio-beam 0.3.3.

Here's a build + test log which illustrates the issue: https://gist.github.com/r-rmcgibbo/49867e8acad2f2476f539310f559ddd1

I apologize if I've misdiagnosed the issue or if this has already been reported. Any help would be appreciated.

**Comment by e-koch** [comment]
Thanks for reporting @rmcgibbo! We've fixed this here: https://github.com/radio-astro-tools/spectral-cube/blob/master/spectral_cube/tests/test_spectral_cube.py#L2006, but it was after the v0.5 release you're building with.

**Comment by rmcgibbo** [comment]
Great. Thanks!
