### ISSUE TITLE
Update installation instructions to include scipy in list of required packages

### ISSUE THREAD

**Issue by hstewart93** [radio-astro-tools/spectral-cube#722]
Encountered bug when using `subcube_from_regions` method where scipy could not be installed. Scipy was not included in required packages.

**Comment by keflavich** [comment]
Both scipy and regions are listed as optional requirements in setup.cfg.  Regions is listed as an optional dependency here:
https://spectral-cube.readthedocs.io/en/latest/installing.html#requirements
but scipy isn't and should be.

The relevant lines that require scipy are:
https://github.com/radio-astro-tools/spectral-cube/blob/606b1eff79c8e3ecfbb8cb9b5af3a4fa8d6efbcd/spectral_cube/spectral_cube.py#L1884-L1885

**Comment by keflavich** [comment]
Closed by #724
