### ISSUE TITLE
Auto-broadcast boolean masks

### ISSUE THREAD

**Issue by ChrisBeaumont** [radio-astro-tools/spectral-cube#75]
#73 adds the ability to pass a 3D boolean array into `with_mask`, which is auto-wrapped into a `BooleanArrayMask`. We should extend this to auto-broadcast 1D or 2D masks. This would make it easy to apply masks derived from moment maps:

```
mask = cube.moment0() > 5
mom1 = cube.with_mask(mask).moment1()
```

**Comment by keflavich** [comment]
I think this is closed by https://github.com/radio-astro-tools/spectral-cube/pull/115
