### ISSUE TITLE
Example header which doesn't grab bunit

### ISSUE THREAD

**Issue by ChrisBeaumont** [radio-astro-tools/spectral-cube#77]
Relevant header line:

```
BUNIT   = '   K    '           / TA*   
```

```
In [2]: read('12co.fits').unit
WARNING: FITSFixedWarning: 'spcfix' made the change 'Changed CTYPE3 from 'VELO-LSR' to 'VOPT', and SPECSYS to 'LSRK''. [astropy.wcs.wcs]
Out[2]: Unit(dimensionless)
```

**Comment by keflavich** [comment]
This is getting closed as a 'noncompliant FITS file' issue.  If we start encountering these in the wild frequently, we can implement a workaround, but I don't believe it's necessary now.

**Comment by HugoDelgado** [comment]
I have a fits with this header
CTYPE3  = 'VELO-LSR'                                            /  3rd axis type
CRVAL3  =       -188079.390625 /  Reference pixel value                         
CRPIX3  =                    1 /  Reference pixel                               
CDELT3  =        736.125000000 /  Pixel size in world coordinate units          
CROTA3  =               0.0000 /  Axis rotation in degrees                      
EQUINOX =              2000.00 /  Equinox of coordinates (if any)               
BUNIT   = 'K (Tb)'                                 /  Units of pixel data values

Im getting this error and it might be changing the units of my axis and labels. 
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
WARNING: FITSFixedWarning: 'spcfix' made the change 'Changed CTYPE3 from 'VELO-LSR' to 'VOPT', and SPECSYS to 'LSRK' (VELREF=0)'. [astropy.wcs.wcs]

**Comment by keflavich** [comment]
Yeah, this (`BUNIT = 'K (Tb)') is a _very_ common special case because of GILDAS CLASS and I think we should handle it.

The warnings are not entirely relevant, though note that GILDAS-CLASS does not conform to the FITS WCS paper recommendations and that's why we're getting warnings.
