### ISSUE TITLE
Question about writing BUNIT as 'Jy/beam' instead of 'beam-1 Jy'

### ISSUE THREAD

**Issue by spectram** [radio-astro-tools/spectral-cube#806]
SpectralCube.write() seems to save BUNIT as 'beam-1 Jy'. This is creating issues running SoFiA2. The space after beam-1 also makes parsing unnecessarily cumbersome.

**Comment by keflavich** [comment]
What's SoFiA2?

Unfortunately, that format is what is expected in the FITS standard:
```python
>>> from astropy import units as u
>>> (u.Jy/u.beam).to_string('FITS')
'beam-1 Jy'
```

Since this is an upstream issue (it is coming directly from astropy), I suggest opening an issue there.

**Comment by spectram** [comment]
SoFiA is an HI source finding tool. https://github.com/SoFiA-Admin/SoFiA-2
I will first check with SoFiA2 authors before raising the issue in Astropy. I reckon there to be other factors involved.
