### ISSUE TITLE
``filled_data`` does not act as array if not sliced

### ISSUE THREAD

**Issue by astrofrog** [radio-astro-tools/spectral-cube#81]
`cube.filled_data` does not act like an array if not sliced:

```
>>> cube.filled_data.shape
...
AttributeError: 'SliceIndexer' object has no attribute 'shape'
```

Maybe we can pass all requested attributes to the underlying data?

**Comment by e-koch** [comment]
Some of this was solved at some point:
```
In [3]: cube.filled_data.shape
Out[3]: (77, 1251, 777)
```
Other attributes like `dtype` do not.

@keflavich - thoughts on whether this is effectively "solved"?

**Comment by keflavich** [comment]
yeah, let's call it solved for now.  If we refactor to use ndcube under the hood, this will become doubly irrelevant
