### ISSUE TITLE
Test failures on windows

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/spectral-cube#840]
We have new spontaneous test failures as of a few weeks ago:

https://github.com/radio-astro-tools/spectral-cube/actions/runs/3065719874/jobs/4950103886#step:5:263

**Comment by keflavich** [comment]
https://github.com/dask/distributed/issues/6842 seems to be the same issue.  I think we just need to pin to a specific dask-distributed version

**Comment by e-koch** [comment]
Fixed in #841
