### ISSUE TITLE
moment 2 map

### ISSUE THREAD

**Issue by gvdsteene** [radio-astro-tools/spectral-cube#849]
A moment 2 map is a variance map. How come that I obtain negative values ?

**Comment by keflavich** [comment]
You generally shouldn't, but it is likely to occur when using velocities.  The equation for moment-2 is:
$\frac{\Sigma (y - <y>)^2 x dx}{\Sigma{y dx}}$
If there are X-values that are negative (negative velocities) that get more weight than the positive values, the moment will be negative.  This should not occur if the S/N is high.
