### ISSUE TITLE
'can't set attribute' failures after fixing CI

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/spectral-cube#859]
```python
>       result.mask = _shrink_mask(cond)
E       AttributeError: can't set attribute
```
https://github.com/radio-astro-tools/spectral-cube/actions/runs/3737805509/jobs/6343314107#step:5:423

**Comment by keflavich** [comment]
Also had this issue on the non-np1.24 version:
https://github.com/radio-astro-tools/spectral-cube/actions/runs/3737654149/jobs/6343040164#step:5:340
```python
>       data = function(data_in, *args)
E       TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'floor_divide'>, '__call__', dask.array<FilledArrayHandler d693a33f-fc2f-43c5-9718, shape=(2, 3, 4), dtype=>f8, chunksize=(2, 3, 4), chunktype=numpy.ndarray>, <Quantity 0.5 K>): 'Array', 'Quantity'

../../spectral_cube/spectral_cube.py:942: TypeError
```

**Comment by bsipocz** [comment]
I'm fairly certain this is more related to astropy dev than to numpy 1.24

**Comment by bsipocz** [comment]
I would ping Marten, as it looks related to masks, but that may be a red herring, I didn't dig into any depth for the details.
