### ISSUE TITLE
Question about spectral smoothing

### ISSUE THREAD

**Issue by Antares1234** [radio-astro-tools/spectral-cube#876]
There are some examples of spectral smoothing in the docs, and I am a little confused about the Gaussian kernels in these examples.
<img width="719" alt="image" src="https://user-images.githubusercontent.com/93385817/232072625-c5b5a201-8a66-4889-bb5f-84097cc921eb.png">
It seems that the FWHM of the Gaussian kernel is calculated in different ways in the two examples. The former is 2/0.5, while the latter is (0.25^2 - 0.1^2)^0.5/0.1. Why doesn't the latter use 0.25/0.1 as the FWHM?

**Comment by keflavich** [comment]
The `Gaussian1DKernel` object takes a value in units of pixels.  

When you convolve two Gaussians, the result is a Gaussian with width:
$$\sigma^2_{final} = \sigma^2_{1} + \sigma^2_{2}$$

The first above example is smoothing by 4 pixels FWHM, which smooths _by_ 4 pixels.  If the original data had resolution of 0.1 km/s, this would result in smoothing to (0.1^2 + (4/2.35 * 0.1)^2)^0.5 = 0.197 km/s.  The second example smooths _to_ a target resolution of 0.25 km/s.

**Comment by Antares1234** [comment]
I see. Thanks for your explanation. 
And there is another question. I'm reading the cube projection tutorial: [https://learn.astropy.org/tutorials/SpectralCubeReprojectExample.html](url). 
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/93385817/232189861-1f933077-a065-44b1-809f-3dd4a0d7d8fc.png">
Here the standard deviation of the kernel is 1.886/2.35. Why isn't it divided by the original pixel width (velocity_res_2)?

**Comment by keflavich** [comment]
Good catch, that looks like an error.  It would be helpful to propose a suggested fix there!
