### ISSUE TITLE
Compatibility with Python 3.12

### ISSUE THREAD

**Issue by smaret** [radio-astro-tools/spectral-cube#914]
Spectral-cube fails to build with Python 3.12 because it uses distutils (see nixos/nixpkgs#315078 ). This [patch](https://github.com/GaetanLepage/nixpkgs/blob/aa5aa63be72021dba2ff1782102d8750227d387f/pkgs/development/python-modules/spectral-cube/distutils-looseversion.patch) from @GaetanLepage fixes this issue. Could you please include it in the next release?

**Comment by keflavich** [comment]
This was solved in https://github.com/radio-astro-tools/spectral-cube/pull/901

**Comment by smaret** [comment]
Sorry I missed that. This hasn't been released, right?
